### ISSUE TITLE
Incorrect hint text and cursor color in overview search box

### ISSUE THREAD

**Issue by HymanZHAN** [vinceliuice/Fluent-gtk-theme#122]
Thanks for your work~ Just a small visual bug report: The cursor and hint text in the overview search box seem to be of the wrong color. 

Fluent shell theme:

![image](https://user-images.githubusercontent.com/26806995/187064853-7d3c9731-7e8c-4c9a-8e58-5180c7a52698.png)

Default shell theme:

![Screenshot from 2022-08-28 16-22-22](https://user-images.githubusercontent.com/26806995/187064864-b5221b69-bf98-4c6a-a961-fb918b429c07.png)

Seems to me that the color of the default theme is more legible and thus "correct". I think I know where it's going wrong and can pull up a quick PR.

**Comment by HymanZHAN** [comment]
Ah, wrong estimation. I am not so confident that I can make changes to the source scss files without breaking something I am not aware of. I do know where in the gtk-shell.css file that is breaking the style.

```css
/* for caret color */
#overview .search-entry {
  width: 320px;
  border: none;
  border-radius: 5px;
  /* before: caret-color: rgba(0, 0, 0, 0.75); */
  caret-color: rgba(255, 255, 255, 0.75);
  color: rgba(0, 0, 0, 0.75);
  background-color: rgba(255, 255, 255, 0.75);
  border-color: transparent;
  box-shadow: none;
  selection-background-color: #1A73E8;
  selected-color: #FFFFFF !important;
  margin-top: 12px;
  margin-bottom: 6px;
}

/* for hint text */
#overview .search-entry StLabel.hint-text {
  margin-left: 2px;
  /* before: color: rgba(0, 0, 0, 0.35); */
  color: rgba(255, 255, 255, 0.35);
}
```

After making the above changes to `$HOME/.themes/Fluent/gnome-shell/gnome-shell.css`, the issue is fixed.

![image](https://user-images.githubusercontent.com/26806995/187066253-79fd965d-3872-490d-b69e-5a3f5968f146.png)
